import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { logActivity } from "@/lib/audit";

const schema = z.object({ title: z.string().trim().min(3).max(140), message: z.string().trim().min(5).max(2000), noticeType: z.enum(["RENT_REMINDER", "MAINTENANCE_UPDATE", "WATER_NOTICE", "ELECTRICITY_NOTICE", "RULE_UPDATE", "EMERGENCY"]), targetRole: z.enum(["ADMIN", "TENANT"]).optional().nullable(), ownerId: z.string().optional().nullable(), isImportant: z.boolean().optional().default(false) });
export async function GET() { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Sign in required." }, { status: 401 }); let where = {}; if (user.role === "ADMIN") where = { OR: [{ createdById: user.id }, { ownerId: user.id }, { targetRole: "ADMIN" }, { targetRole: null, ownerId: null }] }; if (user.role === "TENANT") { const tenant = await prisma.user.findUnique({ where: { id: user.id }, select: { adminId: true } }); where = { OR: [{ ownerId: tenant?.adminId || "" }, { targetRole: "TENANT", ownerId: null }, { targetRole: null, ownerId: null }] }; } const notices = await prisma.notice.findMany({ where: { ...where, isDeleted: false }, include: { createdBy: { select: { id: true, name: true, role: true } } }, orderBy: [{ isImportant: "desc" }, { createdAt: "desc" }], take: 100 }); return NextResponse.json({ notices }); }
export async function POST(request: Request) { const user = await getCurrentUser(); if (!user || user.role === "TENANT") return NextResponse.json({ error: "Owner or Master Admin access required." }, { status: 403 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Enter valid notice details." }, { status: 400 }); const ownerId = user.role === "ADMIN" ? user.id : parsed.data.ownerId || null; const targetRole = user.role === "ADMIN" ? "TENANT" : parsed.data.targetRole || null; const notice = await prisma.notice.create({ data: { ...parsed.data, createdById: user.id, ownerId, targetRole }, include: { createdBy: { select: { id: true, name: true, role: true } } } }); const recipients = await prisma.user.findMany({ where: user.role === "ADMIN" ? { role: "TENANT", adminId: user.id, status: "ACTIVE", isDeleted: false } : { ...(targetRole ? { role: targetRole } : {}), ...(ownerId ? { OR: [{ id: ownerId }, { adminId: ownerId }] } : {}), status: "ACTIVE", isDeleted: false }, select: { id: true } }); if (recipients.length) await prisma.notification.createMany({ data: recipients.map((recipient) => ({ userId: recipient.id, title: notice.title, message: notice.message, type: "NOTICE" })) }); await logActivity({ actorId: user.id, actorRole: user.role, action: "NOTICE_CREATED", targetId: notice.id, targetType: "NOTICE", description: `${user.name} posted ${notice.title}.` }); return NextResponse.json({ notice }, { status: 201 }); }
