"use client";

import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Activity, Ban, Building2, CheckCircle2, Clock3, FileWarning, History, Loader2, Mail, MapPin, Search, ShieldCheck, UserCheck, UsersRound, X } from "lucide-react";
import type { AnalyticsData } from "@/components/rental-workflows";
import { RoleInsights } from "@/components/value-features";

type Mode = "overview" | "owners" | "master-tenants" | "support" | "activity";
type Owner = { id: string; name: string; email: string; phone: string | null; status: "ACTIVE" | "PENDING" | "BLOCKED"; createdAt: string; updatedAt: string; tenants: Array<{ id: string; name: string; email: string; status: string }>; propertiesOwned: Array<{ id: string; name: string; address: string; status: string }>; _count: { tenants: number; administeredBills: number; administeredRent: number; administeredDocuments: number; propertiesOwned: number } };
type Tenant = { id: string; name: string; email: string; ageGroup: string | null; status: string; createdAt: string; admin: { id: string; name: string; email: string; status: string } | null; tenantRent: Array<{ id: string; amount: number; tenantPaymentStatus: string; adminVerificationStatus: string }>; tenantBills: Array<{ id: string; billType: string; amount: number; tenantPaymentStatus: string; adminVerificationStatus: string }>; tenantDocuments: Array<{ id: string; kind: string; fileName: string; status: string; createdAt: string }>; complaintsRaised: Array<{ id: string; status: string; priority: string }>; propertiesRented: Array<{ id: string; name: string; address: string; unit: string | null; status: string }> };
type Report = { id: string; name: string | null; email: string; role: string | null; issueType: string; description: string; status: "OPEN" | "IN_PROGRESS" | "RESOLVED" | "REJECTED"; adminNote: string | null; createdAt: string; updatedAt: string };
type Log = { id: string; actorId: string | null; actorRole: string | null; action: string; targetId: string | null; targetType: string | null; description: string; createdAt: string; actor: { id: string; name: string; email: string; role: string } | null };

async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...options?.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to continue."); return data; }
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
const shortDate = (value: string) => new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function MasterAdminConsole({ mode, analytics, notify }: { mode: Mode; analytics: AnalyticsData | null; notify: (type: "success" | "error", text: string) => void }) {
  const [owners, setOwners] = useState<Owner[]>([]); const [tenants, setTenants] = useState<Tenant[]>([]); const [reports, setReports] = useState<Report[]>([]); const [logs, setLogs] = useState<Log[]>([]); const [actions, setActions] = useState<string[]>([]);
  const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [ownerId, setOwnerId] = useState("ALL"); const [role, setRole] = useState("ALL"); const [action, setAction] = useState("ALL"); const [from, setFrom] = useState(""); const [selectedOwner, setSelectedOwner] = useState<Owner | null>(null); const [selectedTenant, setSelectedTenant] = useState<Tenant | null>(null); const [confirmOwner, setConfirmOwner] = useState<{ owner: Owner; status: Owner["status"] } | null>(null); const [notes, setNotes] = useState<Record<string, string>>({}); const [busy, setBusy] = useState("");

  useEffect(() => { Promise.all([api<{ owners: Owner[] }>("/api/master/owners"), api<{ tenants: Tenant[] }>("/api/master/tenants"), api<{ reports: Report[] }>("/api/master/support"), api<{ logs: Log[]; actions: string[] }>("/api/master/activity")]).then(([ownerData, tenantData, reportData, activityData]) => { setOwners(ownerData.owners); setTenants(tenantData.tenants); setReports(reportData.reports); setLogs(activityData.logs); setActions(activityData.actions); setNotes(Object.fromEntries(reportData.reports.map((item) => [item.id, item.adminNote || ""]))); }).catch((error) => notify("error", error instanceof Error ? error.message : "Unable to load command-center data.")).finally(() => setLoading(false)); }, [notify]);
  useEffect(() => { setSearch(""); setStatus("ALL"); setOwnerId("ALL"); setRole("ALL"); setAction("ALL"); setFrom(""); }, [mode]);

  const filteredOwners = useMemo(() => owners.filter((item) => (status === "ALL" || item.status === status) && `${item.name} ${item.email}`.toLowerCase().includes(search.toLowerCase())), [owners, search, status]);
  const filteredTenants = useMemo(() => tenants.filter((item) => (ownerId === "ALL" || item.admin?.id === ownerId) && `${item.name} ${item.email} ${item.admin?.name || ""}`.toLowerCase().includes(search.toLowerCase())), [tenants, search, ownerId]);
  const filteredReports = useMemo(() => reports.filter((item) => status === "ALL" || item.status === status), [reports, status]);
  const filteredLogs = useMemo(() => logs.filter((item) => (role === "ALL" || item.actorRole === role) && (action === "ALL" || item.action === action) && (!ownerId || ownerId === "ALL" || item.actorId === ownerId) && (!from || new Date(item.createdAt) >= new Date(`${from}T00:00:00`))), [logs, role, action, ownerId, from]);

  async function changeOwnerStatus() { if (!confirmOwner) return; setBusy(confirmOwner.owner.id); try { const data = await api<{ owner: Pick<Owner, "id" | "status"> }>(`/api/master/owners/${confirmOwner.owner.id}`, { method: "PATCH", body: JSON.stringify({ status: confirmOwner.status }) }); setOwners((current) => current.map((item) => item.id === data.owner.id ? { ...item, status: data.owner.status } : item)); notify("success", `${confirmOwner.owner.name} is now ${confirmOwner.status.toLowerCase()}.`); setConfirmOwner(null); } catch (error) { notify("error", error instanceof Error ? error.message : "Unable to update owner."); } finally { setBusy(""); } }
  async function updateReport(report: Report, nextStatus: Report["status"]) { setBusy(report.id); try { const data = await api<{ report: Report }>(`/api/master/support/${report.id}`, { method: "PATCH", body: JSON.stringify({ status: nextStatus, adminNote: notes[report.id] || "" }) }); setReports((current) => current.map((item) => item.id === report.id ? data.report : item)); notify("success", "Support report updated."); } catch (error) { notify("error", error instanceof Error ? error.message : "Unable to update report."); } finally { setBusy(""); } }

  if (loading) return <div className="master-skeleton-grid">{Array.from({ length: 8 }).map((_, index) => <span key={index} />)}</div>;
  if (mode === "overview") return <MasterOverview analytics={analytics} owners={owners} reports={reports} logs={logs} />;
  if (mode === "owners") return <div className="view-stack"><Header kicker="Account governance" title="Owner management" text="Approve, inspect, block, and restore owner accounts from one protected directory." /><Filters search={search} setSearch={setSearch} status={status} setStatus={setStatus} statuses={["ALL", "ACTIVE", "PENDING", "BLOCKED"]} />
    <section className="master-table-card"><table className="master-table"><thead><tr><th>Owner</th><th>Status</th><th>Portfolio</th><th>Records</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{filteredOwners.map((owner) => <tr key={owner.id}><td><button className="identity-button" onClick={() => setSelectedOwner(owner)}><Avatar name={owner.name} /><span><b>{owner.name}</b><small>{owner.email}</small></span></button></td><td><Badge value={owner.status} /></td><td>{owner._count.tenants} tenants · {owner._count.propertiesOwned} properties</td><td>{owner._count.administeredRent} rent · {owner._count.administeredBills} bills · {owner._count.administeredDocuments} docs</td><td>{shortDate(owner.createdAt)}</td><td className="master-actions"><button onClick={() => setSelectedOwner(owner)}>View</button>{owner.status === "PENDING" && <button onClick={() => setConfirmOwner({ owner, status: "ACTIVE" })}><UserCheck />Approve</button>}{owner.status === "BLOCKED" ? <button onClick={() => setConfirmOwner({ owner, status: "ACTIVE" })}><CheckCircle2 />Unblock</button> : <button className="danger-soft" onClick={() => setConfirmOwner({ owner, status: "BLOCKED" })}><Ban />Block</button>}</td></tr>)}</tbody></table>{!filteredOwners.length && <Empty text="No owners match these filters." />}</section>
    {selectedOwner && <Drawer title="Owner profile" onClose={() => setSelectedOwner(null)}><div className="profile-hero"><Avatar name={selectedOwner.name} /><div><h3>{selectedOwner.name}</h3><p>{selectedOwner.email}</p><Badge value={selectedOwner.status} /></div></div><ProfileStats values={[["Tenants", selectedOwner._count.tenants], ["Properties", selectedOwner._count.propertiesOwned], ["Rent records", selectedOwner._count.administeredRent], ["Bills", selectedOwner._count.administeredBills], ["Documents", selectedOwner._count.administeredDocuments]]} /><h4>Linked tenants</h4>{selectedOwner.tenants.map((tenant) => <article className="mini-record" key={tenant.id}><UsersRound /><span><b>{tenant.name}</b><small>{tenant.email}</small></span><Badge value={tenant.status} /></article>)}<h4>Properties</h4>{selectedOwner.propertiesOwned.map((property) => <article className="mini-record" key={property.id}><MapPin /><span><b>{property.name}</b><small>{property.address}</small></span></article>)}</Drawer>}
    {confirmOwner && <Confirm title={`${label(confirmOwner.status)} ${confirmOwner.owner.name}?`} text={confirmOwner.status === "BLOCKED" ? "This immediately prevents owner sign-in and tenant management until restored." : "This restores secure owner access."} busy={busy === confirmOwner.owner.id} onCancel={() => setConfirmOwner(null)} onConfirm={changeOwnerStatus} />}</div>;
  if (mode === "master-tenants") return <div className="view-stack"><Header kicker="Portfolio visibility" title="All tenants" text="Every tenant remains linked to exactly one owner while Master Admin retains global read-only visibility." /><section className="master-filter-bar"><label><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tenant, email, or owner" /></label><select aria-label="Filter by owner" value={ownerId} onChange={(event) => setOwnerId(event.target.value)}><option value="ALL">All owners</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></section><section className="master-card-grid">{filteredTenants.map((tenant) => { const score = reliability(tenant); return <motion.button whileHover={{ y: -3 }} className="master-person-card" key={tenant.id} onClick={() => setSelectedTenant(tenant)}><Avatar name={tenant.name} /><div><h3>{tenant.name}</h3><p>{tenant.email}</p></div><Badge value={tenant.status} /><small>Owner: {tenant.admin?.name || "Unassigned"} · Reliability {score.value}/100 ({score.label})</small><span>{tenant.tenantRent.length} rent · {tenant.tenantBills.length} bills · {tenant.tenantDocuments.length} documents</span></motion.button>; })}</section>{!filteredTenants.length && <Empty text="No tenants match these filters." />}
    {selectedTenant && <Drawer title="Tenant profile" onClose={() => setSelectedTenant(null)}><div className="profile-hero"><Avatar name={selectedTenant.name} /><div><h3>{selectedTenant.name}</h3><p>{selectedTenant.email}</p><Badge value={selectedTenant.status} /></div></div><article className="owner-link"><Building2 /><div><small>Linked owner</small><b>{selectedTenant.admin?.name || "Unassigned"}</b><p>{selectedTenant.admin?.email}</p></div></article><ProfileStats values={[["Rent records", selectedTenant.tenantRent.length], ["Bills", selectedTenant.tenantBills.length], ["Documents", selectedTenant.tenantDocuments.length], ["Properties", selectedTenant.propertiesRented.length]]} /><h4>Rental status</h4>{selectedTenant.tenantRent.map((rent) => <article className="mini-record" key={rent.id}><Activity /><span><b>₹{Number(rent.amount).toLocaleString("en-IN")}</b><small>{label(rent.tenantPaymentStatus)} · {label(rent.adminVerificationStatus)}</small></span></article>)}<h4>Documents</h4>{selectedTenant.tenantDocuments.map((document) => <article className="mini-record" key={document.id}><ShieldCheck /><span><b>{label(document.kind)}</b><small>{document.fileName}</small></span><Badge value={document.status} /></article>)}</Drawer>}</div>;
  if (mode === "support") return <div className="view-stack"><Header kicker="Access assistance" title="Issue reports" text="Triage login, signup, owner discovery, approval, and password-recovery problems." /><section className="report-summary"><span><FileWarning /><b>{reports.length}</b>Total</span><span><Clock3 /><b>{reports.filter((item) => item.status === "OPEN").length}</b>Open</span><span><CheckCircle2 /><b>{reports.filter((item) => item.status === "RESOLVED").length}</b>Resolved</span></section><Filters search="" setSearch={() => {}} status={status} setStatus={setStatus} statuses={["ALL", "OPEN", "IN_PROGRESS", "RESOLVED", "REJECTED"]} hideSearch /><section className="report-list">{filteredReports.map((report) => <article key={report.id}><header><div><b>{report.name || "Anonymous user"}</b><span>{report.email}</span></div><Badge value={report.status} /></header><small>{label(report.issueType)} · {report.role ? label(report.role) : "Role not selected"} · {shortDate(report.createdAt)}</small><p>{report.description}</p><label>Master Admin note<textarea value={notes[report.id] || ""} onChange={(event) => setNotes((current) => ({ ...current, [report.id]: event.target.value }))} placeholder="Resolution details or follow-up note" /></label><div><button disabled={busy === report.id} onClick={() => updateReport(report, "IN_PROGRESS")}>In progress</button><button disabled={busy === report.id} onClick={() => updateReport(report, "RESOLVED")}>Resolve</button><button className="danger-soft" disabled={busy === report.id} onClick={() => updateReport(report, "REJECTED")}>Reject</button></div></article>)}</section>{!filteredReports.length && <Empty text="No reports match this status." />}</div>;
  return <div className="view-stack"><Header kicker="Security audit" title="Activity history" text="A time-ordered record of authentication, registration, payment, documents, account controls, and reports." /><section className="master-filter-bar audit"><select aria-label="Filter activity role" value={role} onChange={(event) => setRole(event.target.value)}><option value="ALL">All roles</option><option value="MASTER_ADMIN">Master Admin</option><option value="ADMIN">Owner / Admin</option><option value="TENANT">Tenant</option></select><select aria-label="Filter activity type" value={action} onChange={(event) => setAction(event.target.value)}><option value="ALL">All activity types</option>{actions.map((item) => <option value={item} key={item}>{label(item)}</option>)}</select><select aria-label="Filter activity owner" value={ownerId} onChange={(event) => setOwnerId(event.target.value)}><option value="ALL">All owners</option>{owners.map((owner) => <option value={owner.id} key={owner.id}>{owner.name}</option>)}</select><input aria-label="Activity from date" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></section><section className="audit-timeline">{filteredLogs.map((log) => <article key={log.id}><span><History /></span><div><header><b>{label(log.action)}</b><small>{shortDate(log.createdAt)}</small></header><p>{log.description}</p><small>{log.actor ? `${log.actor.name} · ${label(log.actor.role)}` : "Public / system action"}{log.targetType ? ` · ${label(log.targetType)}` : ""}</small></div></article>)}</section>{!filteredLogs.length && <Empty text="No activity matches these filters." />}</div>;
}

function MasterOverview({ analytics, owners, reports, logs }: { analytics: AnalyticsData | null; owners: Owner[]; reports: Report[]; logs: Log[] }) { const stats = analytics?.stats || {}; const cards = [["Owners", stats.admins], ["Tenants", stats.tenants], ["Properties", stats.properties], ["Rent records", stats.rentRecords], ["Electricity bills", stats.electricityBills], ["Water bills", stats.waterBills], ["Paid rent", stats.paidRent], ["Unpaid rent", stats.unpaidRent], ["Overdue rent", stats.overdueRent], ["Tenant marked paid", stats.tenantMarkedPaid], ["Admin verified", stats.verifiedPaid], ["Rejected claims", stats.rejectedClaims], ["Pending verification", stats.pendingVerification], ["ID proofs", stats.idProofs], ["Verified IDs", stats.verifiedIdProofs], ["Rejected IDs", stats.rejectedIdProofs], ["E-agreements", stats.agreements], ["Verified agreements", stats.verifiedAgreements], ["Rejected agreements", stats.rejectedAgreements], ["Support reports", stats.totalSupport]]; return <div className="view-stack"><section className="master-command-hero"><div><p>Protected portfolio intelligence</p><h2>Master Admin command center</h2><span>Live control across owners, tenants, records, documents, and account security.</span></div><ShieldCheck /></section><RoleInsights role="MASTER_ADMIN" rents={[]} documents={[]} analytics={analytics} /><section className="master-stat-matrix">{cards.map(([name, value], index) => <motion.article initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .025 }} key={String(name)}><small>{name}</small><strong>{value ?? 0}</strong></motion.article>)}</section><div className="master-overview-grid"><section className="content-card"><h3>Owner performance</h3><div className="owner-performance">{owners.slice().sort((a,b) => b._count.tenants - a._count.tenants).map((owner) => <article key={owner.id}><Avatar name={owner.name} /><div><b>{owner.name}</b><small>{owner._count.tenants} tenants · {owner._count.administeredRent + owner._count.administeredBills} records</small></div><Badge value={owner.status} /></article>)}</div></section><section className="content-card"><h3>Support pulse</h3><div className="support-pulse"><span><Clock3 />{reports.filter((item) => item.status === "OPEN").length} open reports</span><span><UserCheck />{owners.filter((item) => item.status === "PENDING").length} owners awaiting approval</span><span><Ban />{owners.filter((item) => item.status === "BLOCKED").length} blocked owners</span></div></section></div><section className="content-card"><h3>Recent activity</h3><div className="compact-timeline">{logs.slice(0, 8).map((log) => <article key={log.id}><span><Activity /></span><div><b>{label(log.action)}</b><p>{log.description}</p></div><small>{shortDate(log.createdAt)}</small></article>)}</div></section></div>; }
function Header({ kicker, title, text }: { kicker: string; title: string; text: string }) { return <section className="view-heading"><div><p className="kicker">{kicker}</p><h2>{title}</h2><p>{text}</p></div></section>; }
function Filters({ search, setSearch, status, setStatus, statuses, hideSearch = false }: { search: string; setSearch: (value: string) => void; status: string; setStatus: (value: string) => void; statuses: string[]; hideSearch?: boolean }) { return <section className="master-filter-bar">{!hideSearch && <label><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or email" /></label>}<select aria-label="Filter by status" value={status} onChange={(event) => setStatus(event.target.value)}>{statuses.map((item) => <option key={item} value={item}>{item === "ALL" ? "All statuses" : label(item)}</option>)}</select></section>; }
function Badge({ value }: { value: string }) { return <span className={`master-badge ${value.toLowerCase()}`}>{label(value)}</span>; }
function Avatar({ name }: { name: string }) { return <span className="avatar">{name.split(" ").slice(0,2).map((part) => part[0]).join("")}</span>; }
function Empty({ text }: { text: string }) { return <div className="empty-state"><span><Search /></span><h3>Nothing to show</h3><p>{text}</p></div>; }
function ProfileStats({ values }: { values: Array<[string, number]> }) { return <div className="profile-stats">{values.map(([name, value]) => <span key={name}><b>{value}</b><small>{name}</small></span>)}</div>; }
function Drawer({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="master-drawer"><header><h2>{title}</h2><button onClick={onClose} aria-label="Close profile"><X /></button></header>{children}</aside></div>; }
function Confirm({ title, text, busy, onCancel, onConfirm }: { title: string; text: string; busy: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="modal-backdrop"><section className="confirm-modal master-confirm"><span><ShieldCheck /></span><h2>{title}</h2><p>{text}</p><div><button onClick={onCancel}>Cancel</button><button className="danger-button" disabled={busy} onClick={onConfirm}>{busy ? <Loader2 className="spin" /> : "Confirm change"}</button></div></section></div>; }
function reliability(tenant: Tenant) { const verifiedRent = tenant.tenantRent.filter((item) => item.adminVerificationStatus === "VERIFIED_PAID").length; const overdue = tenant.tenantRent.filter((item) => item.adminVerificationStatus === "OVERDUE").length; const rejected = [...tenant.tenantRent, ...tenant.tenantBills].filter((item) => item.adminVerificationStatus === "REJECTED_CLAIM").length; const verifiedDocs = tenant.tenantDocuments.filter((item) => item.status === "VERIFIED").length; const openComplaints = tenant.complaintsRaised.filter((item) => item.status === "NEW" || item.status === "IN_PROGRESS").length; const value = Math.max(0, Math.min(100, 60 + verifiedRent * 8 + verifiedDocs * 8 - overdue * 12 - rejected * 10 - openComplaints * 5)); return { value, label: value >= 90 ? "Excellent" : value >= 75 ? "Good" : value >= 60 ? "Average" : "Risk" }; }
